//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.EtoOno
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    //  *** Start programmer edit section *** (Using statements)

    //  *** End programmer edit section *** (Using statements)


    /// <summary>
    /// То.
    /// </summary>
    //  *** Start programmer edit section *** (То CustomAttributes)

    //  *** End programmer edit section *** (То CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("ТоE", new string[] {
            "Что as \'Что\'",
            "Когда as \'Когда\'"})]
    public class То : ICSSoft.STORMNET.DataObject
    {
        
        private string fЧто;
        
        private string fКогда;
        
        private IIS.EtoOno.Это fЭто;
        
        //  *** Start programmer edit section *** (То CustomMembers)

        //  *** End programmer edit section *** (То CustomMembers)

        
        /// <summary>
        /// Что.
        /// </summary>
        //  *** Start programmer edit section *** (То.Что CustomAttributes)

        //  *** End programmer edit section *** (То.Что CustomAttributes)
        [StrLen(255)]
        public virtual string Что
        {
            get
            {
                //  *** Start programmer edit section *** (То.Что Get start)

                //  *** End programmer edit section *** (То.Что Get start)
                string result = this.fЧто;
                //  *** Start programmer edit section *** (То.Что Get end)

                //  *** End programmer edit section *** (То.Что Get end)
                return result;
            }
            set
            {
                //  *** Start programmer edit section *** (То.Что Set start)

                //  *** End programmer edit section *** (То.Что Set start)
                this.fЧто = value;
                //  *** Start programmer edit section *** (То.Что Set end)

                //  *** End programmer edit section *** (То.Что Set end)
            }
        }
        
        /// <summary>
        /// Когда.
        /// </summary>
        //  *** Start programmer edit section *** (То.Когда CustomAttributes)

        //  *** End programmer edit section *** (То.Когда CustomAttributes)
        [StrLen(255)]
        public virtual string Когда
        {
            get
            {
                //  *** Start programmer edit section *** (То.Когда Get start)

                //  *** End programmer edit section *** (То.Когда Get start)
                string result = this.fКогда;
                //  *** Start programmer edit section *** (То.Когда Get end)

                //  *** End programmer edit section *** (То.Когда Get end)
                return result;
            }
            set
            {
                //  *** Start programmer edit section *** (То.Когда Set start)

                //  *** End programmer edit section *** (То.Когда Set start)
                this.fКогда = value;
                //  *** Start programmer edit section *** (То.Когда Set end)

                //  *** End programmer edit section *** (То.Когда Set end)
            }
        }
        
        /// <summary>
        /// мастеровая ссылка на шапку IIS.EtoOno.Это.
        /// </summary>
        //  *** Start programmer edit section *** (То.Это CustomAttributes)

        //  *** End programmer edit section *** (То.Это CustomAttributes)
        [Agregator()]
        [NotNull()]
        public virtual IIS.EtoOno.Это Это
        {
            get
            {
                //  *** Start programmer edit section *** (То.Это Get start)

                //  *** End programmer edit section *** (То.Это Get start)
                IIS.EtoOno.Это result = this.fЭто;
                //  *** Start programmer edit section *** (То.Это Get end)

                //  *** End programmer edit section *** (То.Это Get end)
                return result;
            }
            set
            {
                //  *** Start programmer edit section *** (То.Это Set start)

                //  *** End programmer edit section *** (То.Это Set start)
                this.fЭто = value;
                //  *** Start programmer edit section *** (То.Это Set end)

                //  *** End programmer edit section *** (То.Это Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "ТоE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ТоE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ТоE", typeof(IIS.EtoOno.То));
                }
            }
        }
    }
    
    /// <summary>
    /// Detail array of То.
    /// </summary>
    //  *** Start programmer edit section *** (DetailArrayDetailArrayOfТо CustomAttributes)

    //  *** End programmer edit section *** (DetailArrayDetailArrayOfТо CustomAttributes)
    public class DetailArrayOfТо : ICSSoft.STORMNET.DetailArray
    {
        
        //  *** Start programmer edit section *** (IIS.EtoOno.DetailArrayOfТо members)

        //  *** End programmer edit section *** (IIS.EtoOno.DetailArrayOfТо members)

        
        /// <summary>
        /// Construct detail array.
        /// </summary>
        /// <summary>
        /// Returns object with type То by index.
        /// </summary>
        /// <summary>
        /// Adds object with type То.
        /// </summary>
        public DetailArrayOfТо(IIS.EtoOno.Это fЭто) : 
                base(typeof(То), ((ICSSoft.STORMNET.DataObject)(fЭто)))
        {
        }
        
        public IIS.EtoOno.То this[int index]
        {
            get
            {
                return ((IIS.EtoOno.То)(this.ItemByIndex(index)));
            }
        }
        
        public virtual void Add(IIS.EtoOno.То dataobject)
        {
            this.AddObject(((ICSSoft.STORMNET.DataObject)(dataobject)));
        }
    }
}
