//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.EtoOno
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    //  *** Start programmer edit section *** (Using statements)

    //  *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Это.
    /// </summary>
    //  *** Start programmer edit section *** (Это CustomAttributes)

    //  *** End programmer edit section *** (Это CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("ЭтоE", new string[] {
            "Арбуз as \'Арбуз\'",
            "Что as \'Что\'",
            "Оно as \'Оно\'",
            "Оно.Да as \'Да\'"}, Hidden=new string[] {
            "Оно.Да"})]
    [AssociatedDetailViewAttribute("ЭтоE", "То", "ТоE", true, "", "То", true, new string[] {
            ""})]
    [MasterViewDefineAttribute("ЭтоE", "Оно", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "Да")]
    [View("ЭтоL", new string[] {
            "Арбуз as \'Арбуз\'",
            "Что as \'Что\'",
            "Оно.Да as \'Да\'"})]
    public class Это : ICSSoft.STORMNET.DataObject
    {
        
        private string fАрбуз;
        
        private int fЧто;
        
        private IIS.EtoOno.Оно fОно;
        
        private IIS.EtoOno.DetailArrayOfТо fТо;
        
        //  *** Start programmer edit section *** (Это CustomMembers)

        //  *** End programmer edit section *** (Это CustomMembers)

        
        /// <summary>
        /// Арбуз.
        /// </summary>
        //  *** Start programmer edit section *** (Это.Арбуз CustomAttributes)

        //  *** End programmer edit section *** (Это.Арбуз CustomAttributes)
        [StrLen(255)]
        public virtual string Арбуз
        {
            get
            {
                //  *** Start programmer edit section *** (Это.Арбуз Get start)

                //  *** End programmer edit section *** (Это.Арбуз Get start)
                string result = this.fАрбуз;
                //  *** Start programmer edit section *** (Это.Арбуз Get end)

                //  *** End programmer edit section *** (Это.Арбуз Get end)
                return result;
            }
            set
            {
                //  *** Start programmer edit section *** (Это.Арбуз Set start)

                //  *** End programmer edit section *** (Это.Арбуз Set start)
                this.fАрбуз = value;
                //  *** Start programmer edit section *** (Это.Арбуз Set end)

                //  *** End programmer edit section *** (Это.Арбуз Set end)
            }
        }
        
        /// <summary>
        /// Что.
        /// </summary>
        //  *** Start programmer edit section *** (Это.Что CustomAttributes)

        //  *** End programmer edit section *** (Это.Что CustomAttributes)
        public virtual int Что
        {
            get
            {
                //  *** Start programmer edit section *** (Это.Что Get start)

                //  *** End programmer edit section *** (Это.Что Get start)
                int result = this.fЧто;
                //  *** Start programmer edit section *** (Это.Что Get end)

                //  *** End programmer edit section *** (Это.Что Get end)
                return result;
            }
            set
            {
                //  *** Start programmer edit section *** (Это.Что Set start)

                //  *** End programmer edit section *** (Это.Что Set start)
                this.fЧто = value;
                //  *** Start programmer edit section *** (Это.Что Set end)

                //  *** End programmer edit section *** (Это.Что Set end)
            }
        }
        
        /// <summary>
        /// Это.
        /// </summary>
        //  *** Start programmer edit section *** (Это.Оно CustomAttributes)

        //  *** End programmer edit section *** (Это.Оно CustomAttributes)
        [NotNull()]
        public virtual IIS.EtoOno.Оно Оно
        {
            get
            {
                //  *** Start programmer edit section *** (Это.Оно Get start)

                //  *** End programmer edit section *** (Это.Оно Get start)
                IIS.EtoOno.Оно result = this.fОно;
                //  *** Start programmer edit section *** (Это.Оно Get end)

                //  *** End programmer edit section *** (Это.Оно Get end)
                return result;
            }
            set
            {
                //  *** Start programmer edit section *** (Это.Оно Set start)

                //  *** End programmer edit section *** (Это.Оно Set start)
                this.fОно = value;
                //  *** Start programmer edit section *** (Это.Оно Set end)

                //  *** End programmer edit section *** (Это.Оно Set end)
            }
        }
        
        /// <summary>
        /// Это.
        /// </summary>
        //  *** Start programmer edit section *** (Это.То CustomAttributes)

        //  *** End programmer edit section *** (Это.То CustomAttributes)
        public virtual IIS.EtoOno.DetailArrayOfТо То
        {
            get
            {
                //  *** Start programmer edit section *** (Это.То Get start)

                //  *** End programmer edit section *** (Это.То Get start)
                if ((this.fТо == null))
                {
                    this.fТо = new IIS.EtoOno.DetailArrayOfТо(this);
                }
                IIS.EtoOno.DetailArrayOfТо result = this.fТо;
                //  *** Start programmer edit section *** (Это.То Get end)

                //  *** End programmer edit section *** (Это.То Get end)
                return result;
            }
            set
            {
                //  *** Start programmer edit section *** (Это.То Set start)

                //  *** End programmer edit section *** (Это.То Set start)
                this.fТо = value;
                //  *** Start programmer edit section *** (Это.То Set end)

                //  *** End programmer edit section *** (Это.То Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "ЭтоE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ЭтоE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ЭтоE", typeof(IIS.EtoOno.Это));
                }
            }
            
            /// <summary>
            /// "ЭтоL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ЭтоL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ЭтоL", typeof(IIS.EtoOno.Это));
                }
            }
        }
    }
}
